#!/bin/bash -l

# Create mightybuilder user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
useradd --shell /bin/bash -u "$USER_ID" -G lucky -o -c "" -m mightybuilder
export HOME=/home/mightybuilder
export USER=mightybuilder
export LOGNAME=mightybuilder
export MAIL=/var/spool/mail/mightybuilder
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/mightybuilder/bin
cp -R /etc/skel $HOME && chown -R mightybuilder:mightybuilder $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel
cd $HOME || exit

# Copy the h2_scf_hf test as example in HOME
mkdir -p $HOME/examples/h2
cp /mrchem/tests/h2_scf_hf/mrchem.inp $HOME/examples/h2/mrchem.inp

# Copy the h2o_energy_blyp test as example in HOME
mkdir -p $HOME/examples/h2o
cp /mrchem/tests/h2o_energy_blyp/mrchem.inp $HOME/examples/h2o/mrchem.inp
cp -R /mrchem/tests/h2o_energy_blyp/initial_guess $HOME/examples/h2o/initial_guess

chown -R mightybuilder:mightybuilder $HOME

# Source everything that needs to be.
# shellcheck disable=SC1091
. /opt/docker/bin/entrypoint_source

# Run whatever the user wants.
exec gosu mightybuilder "$@"
